# Generated by Django 5.2.15 on 2026-06-16 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_userstrike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characteristic',
            options={'verbose_name': 'Характеристика', 'verbose_name_plural': 'Характеристики'},
        ),
        migrations.AlterModelOptions(
            name='characteristichistory',
            options={'verbose_name': 'История характеристики', 'verbose_name_plural': 'История характеристик'},
        ),
        migrations.AlterModelOptions(
            name='ratinglog',
            options={'verbose_name': 'Запись рейтинга', 'verbose_name_plural': 'Журнал рейтинга'},
        ),
        migrations.RenameIndex(
            model_name='ratinglog',
            new_name='progress_ra_user_id_1aca4c_idx',
            old_name='apps_progre_user_id_6c3211_idx',
        ),
        migrations.RenameIndex(
            model_name='ratinglog',
            new_name='progress_ra_source_4f3ca6_idx',
            old_name='apps_progre_source_042e13_idx',
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='current',
            field=models.FloatField(default=0, verbose_name='Текущее значение'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='peak',
            field=models.FloatField(default=0, verbose_name='Пик'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='pillar',
            field=models.CharField(db_index=True, max_length=32, verbose_name='Опора'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='characteristichistory',
            name='characteristic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='progress.characteristic', verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='characteristichistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='characteristichistory',
            name='formula_version',
            field=models.CharField(default='v1', max_length=32, verbose_name='Версия формулы'),
        ),
        migrations.AlterField(
            model_name='characteristichistory',
            name='value',
            field=models.FloatField(verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='ratinglog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='ratinglog',
            name='delta',
            field=models.IntegerField(verbose_name='Изменение'),
        ),
        migrations.AlterField(
            model_name='ratinglog',
            name='reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='ratinglog',
            name='source',
            field=models.CharField(choices=[('quest', 'Квест'), ('badge', 'Значок'), ('shop', 'Магазин'), ('social', 'Социальное'), ('manual', 'Вручную'), ('system', 'Система')], default='system', max_length=16, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='ratinglog',
            name='source_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='ID источника'),
        ),
        migrations.AlterField(
            model_name='ratinglog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='ratinglog',
            name='value_after',
            field=models.IntegerField(verbose_name='Стало'),
        ),
        migrations.AlterField(
            model_name='ratinglog',
            name='value_before',
            field=models.IntegerField(verbose_name='Было'),
        ),
    ]
