# Generated by Django 5.2.17 on 2026-08-27 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_alter_characteristic_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTopicNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.PositiveSmallIntegerField(unique=True, verbose_name='Курс')),
                ('expected_topics', models.PositiveIntegerField(default=0, verbose_name='Ожидаемое число тем')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Нормировка курса',
                'verbose_name_plural': 'Нормировки курсов',
            },
        ),
        migrations.CreateModel(
            name='LXPTopicState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.JSONField(blank=True, default=dict, verbose_name='Темы')),
                ('last_snapshot_date', models.DateField(blank=True, null=True, verbose_name='Последний учтённый снимок')),
                ('baseline_done', models.BooleanField(default=False, verbose_name='База зафиксирована')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lxp_topic_state', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Состояние тем LXP',
                'verbose_name_plural': 'Состояния тем LXP',
            },
        ),
    ]
