# Generated by Django 5.2.17 on 2026-08-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_coursetopicnorm_lxptopicstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratinglog',
            name='source',
            field=models.CharField(choices=[('quest', 'Квест'), ('badge', 'Значок'), ('shop', 'Магазин'), ('social', 'Социальное'), ('drive', 'Движ'), ('manual', 'Вручную'), ('system', 'Система')], default='system', max_length=16, verbose_name='Источник'),
        ),
    ]
