# Generated by Django 5.2.17 on 2026-09-29 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0006_alter_ratinglog_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lxp_class_id', models.CharField(db_index=True, max_length=64, verbose_name='ID занятия в LXP')),
                ('lesson_date', models.DateField(db_index=True, verbose_name='Дата занятия')),
                ('starts_at', models.TimeField(blank=True, null=True, verbose_name='Начало')),
                ('discipline', models.CharField(blank=True, max_length=255, verbose_name='Дисциплина')),
                ('status', models.CharField(choices=[('present', 'Был'), ('online', 'Был онлайн'), ('missed', 'Пропустил')], db_index=True, max_length=16, verbose_name='Отметка')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_attendance', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Посещение занятия',
                'verbose_name_plural': 'Посещения занятий',
                'ordering': ['-lesson_date', 'starts_at'],
                'indexes': [models.Index(fields=['user', 'lesson_date'], name='progress_le_user_id_bf54d0_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'lxp_class_id'), name='uniq_lesson_attendance_user_class')],
            },
        ),
    ]
