# Generated by Django 5.2.15 on 2026-06-16 10:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_hik_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='squad',
            options={'verbose_name': 'Отряд', 'verbose_name_plural': 'Отряды'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'verbose_name': 'Направление', 'verbose_name_plural': 'Направления'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_rating__39f26b_idx',
            old_name='accounts_use_rating__b33500_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_role_1fa9a5_idx',
            old_name='accounts_use_role_a50e43_idx',
        ),
        migrations.AlterField(
            model_name='squad',
            name='capacity',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Вместимость'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='course',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='track',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='callsign',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Позывной'),
        ),
        migrations.AlterField(
            model_name='user',
            name='coins_balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Баланс монет'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hik_card_code',
            field=models.CharField(blank=True, db_index=True, help_text='Код карты / personCode для HikCentral (привязка проходов к пользователю)', max_length=100, null=True, unique=True, verbose_name='Код карты Hik'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hik_person_id',
            field=models.CharField(blank=True, db_index=True, help_text='Идентификатор лица в HikCentral при наличии', max_length=100, null=True, verbose_name='ID лица Hik'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.PositiveIntegerField(default=1, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lxp_user_id',
            field=models.CharField(blank=True, db_index=True, help_text='Идентификатор пользователя в LXP (GraphQL user.id), для связи со снимком', max_length=64, null=True, unique=True, verbose_name='ID в LXP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating_current',
            field=models.PositiveIntegerField(db_index=True, default=300, verbose_name='Текущий рейтинг'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('agent', 'Агент'), ('curator', 'Куратор'), ('tutor', 'Тьютор'), ('admin', 'Админ'), ('hq', 'Штаб')], default='agent', max_length=16, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='squad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.squad', verbose_name='Отряд'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, max_length=64, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='user',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.track', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='user',
            name='unclosed_ct_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Незакрытых КТ'),
        ),
    ]
