services:
  web:
    build:
      context: .
      network: host
  celery:
    build:
      context: .
      network: host
  celery-beat:
    build:
      context: .
      network: host
  frontend:
    build:
      context: ./hero-path-front
      network: host