# Generated by Django 5.2.15 on 2026-06-16 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_hikevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalevent',
            options={'verbose_name': 'Внешнее событие', 'verbose_name_plural': 'Внешние события'},
        ),
        migrations.AlterModelOptions(
            name='hikevent',
            options={'ordering': ['-event_time'], 'verbose_name': 'Событие Hik', 'verbose_name_plural': 'События Hik'},
        ),
        migrations.AlterModelOptions(
            name='lxpsnapshot',
            options={'ordering': ['-date'], 'verbose_name': 'Снимок LXP', 'verbose_name_plural': 'Снимки LXP'},
        ),
        migrations.AlterModelOptions(
            name='telegramaccountlink',
            options={'verbose_name': 'Привязка Telegram', 'verbose_name_plural': 'Привязки Telegram'},
        ),
        migrations.RenameIndex(
            model_name='externalevent',
            new_name='integration_source_3a876c_idx',
            old_name='integrations_source_536f0b_idx',
        ),
        migrations.RenameIndex(
            model_name='hikevent',
            new_name='integration_student_3b8196_idx',
            old_name='hikevent_student_time_idx',
        ),
        migrations.RenameIndex(
            model_name='hikevent',
            new_name='integration_process_20cd68_idx',
            old_name='hikevent_proc_time_idx',
        ),
        migrations.RenameIndex(
            model_name='telegramaccountlink',
            new_name='integration_telegra_400313_idx',
            old_name='apps_integr_telegra_d84461_idx',
        ),
        migrations.AlterField(
            model_name='externalevent',
            name='external_event_id',
            field=models.CharField(max_length=128, verbose_name='Внешний ID'),
        ),
        migrations.AlterField(
            model_name='externalevent',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные'),
        ),
        migrations.AlterField(
            model_name='externalevent',
            name='processed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Обработано'),
        ),
        migrations.AlterField(
            model_name='externalevent',
            name='source',
            field=models.CharField(db_index=True, max_length=32, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='hikevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='hikevent',
            name='door_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Турникет'),
        ),
        migrations.AlterField(
            model_name='hikevent',
            name='event_id',
            field=models.CharField(db_index=True, max_length=128, unique=True, verbose_name='ID события'),
        ),
        migrations.AlterField(
            model_name='hikevent',
            name='event_time',
            field=models.DateTimeField(verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='hikevent',
            name='event_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='hikevent',
            name='processed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Обработано'),
        ),
        migrations.AlterField(
            model_name='hikevent',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Сырые данные'),
        ),
        migrations.AlterField(
            model_name='hikevent',
            name='student_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Код студента'),
        ),
        migrations.AlterField(
            model_name='lxpsnapshot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='lxpsnapshot',
            name='data',
            field=models.JSONField(verbose_name='Данные'),
        ),
        migrations.AlterField(
            model_name='lxpsnapshot',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='telegramaccountlink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='telegramaccountlink',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='telegramaccountlink',
            name='telegram_chat_id',
            field=models.BigIntegerField(db_index=True, verbose_name='Chat ID'),
        ),
        migrations.AlterField(
            model_name='telegramaccountlink',
            name='telegram_user_id',
            field=models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='telegramaccountlink',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя в Telegram'),
        ),
        migrations.AlterField(
            model_name='telegramaccountlink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена'),
        ),
        migrations.AlterField(
            model_name='telegramaccountlink',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
