# Generated by Django 5.2.13 on 2026-08-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_hiksnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='HikImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('web_api', 'Портал (HTTP)'), ('browser', 'Портал (XLSX через браузер)'), ('api', 'HikCentral OpenAPI'), ('snapshot', 'Ручной снимок'), ('manual', 'Ручная загрузка файла')], db_index=True, max_length=16, verbose_name='Режим')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('empty', 'Нет записей'), ('error', 'Ошибка')], db_index=True, max_length=16, verbose_name='Статус')),
                ('date_from', models.DateField(verbose_name='Период с')),
                ('date_to', models.DateField(verbose_name='Период по')),
                ('records_fetched', models.PositiveIntegerField(default=0, verbose_name='Получено записей')),
                ('events_created', models.PositiveIntegerField(default=0, verbose_name='Новых событий')),
                ('external_created', models.PositiveIntegerField(default=0, verbose_name='Создано ExternalEvent')),
                ('users_unmatched', models.PositiveIntegerField(default=0, verbose_name='Без привязки к пользователю')),
                ('relogin_used', models.BooleanField(default=False, verbose_name='Потребовался повторный вход')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='Длительность, мс')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
            ],
            options={
                'verbose_name': 'Запуск импорта Hik',
                'verbose_name_plural': 'Запуски импорта Hik',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at'], name='integration_started_cdec7d_idx'), models.Index(fields=['status', '-started_at'], name='integration_status_27eac2_idx')],
            },
        ),
    ]
