# Generated by Django 5.2.13 on 2026-08-15 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_remove_synthetic_telegram_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='externalevent',
            name='event_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата события'),
        ),
        migrations.AddField(
            model_name='externalevent',
            name='event_type',
            field=models.CharField(blank=True, max_length=32, verbose_name='Тип события'),
        ),
        migrations.AddField(
            model_name='externalevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='externalevent',
            index=models.Index(fields=['user', 'event_date'], name='integration_user_id_519c3d_idx'),
        ),
        migrations.AddIndex(
            model_name='externalevent',
            index=models.Index(fields=['source', 'event_type', 'event_date'], name='integration_source_702dc0_idx'),
        ),
    ]
