# Generated by Django 5.2.13 on 2026-08-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0010_backfill_external_event_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='hikevent',
            name='last_error',
            field=models.TextField(blank=True, verbose_name='Последняя ошибка'),
        ),
        migrations.AddField(
            model_name='hikevent',
            name='process_attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Попыток обработки'),
        ),
    ]
