# Generated by Django 5.2.15 on 2026-06-16 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'verbose_name': 'Значок', 'verbose_name_plural': 'Значки'},
        ),
        migrations.AlterModelOptions(
            name='userbadge',
            options={'verbose_name': 'Значок пользователя', 'verbose_name_plural': 'Значки пользователей'},
        ),
        migrations.RenameIndex(
            model_name='badge',
            new_name='badges_badg_is_acti_4d44bc_idx',
            old_name='apps_badges_is_acti_d5f8d7_idx',
        ),
        migrations.RenameIndex(
            model_name='userbadge',
            new_name='badges_user_user_id_399ac9_idx',
            old_name='apps_badges_user_id_a742a3_idx',
        ),
        migrations.RenameIndex(
            model_name='userbadge',
            new_name='badges_user_user_id_c4e77f_idx',
            old_name='apps_badges_user_id_7d058e_idx',
        ),
        migrations.AlterField(
            model_name='badge',
            name='category',
            field=models.CharField(choices=[('progress', 'Прогресс'), ('social', 'Социальное'), ('academic', 'Учёба'), ('special', 'Особый')], default='progress', max_length=32, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='code',
            field=models.CharField(max_length=64, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='condition',
            field=models.JSONField(blank=True, default=dict, verbose_name='Условие'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='rarity',
            field=models.CharField(choices=[('common', 'Обычный'), ('rare', 'Редкий'), ('epic', 'Эпический'), ('legendary', 'Легендарный')], default='common', max_length=16, verbose_name='Редкость'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='reward_coins',
            field=models.PositiveIntegerField(default=0, verbose_name='Награда (монеты)'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='acquired_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Получен'),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_users', to='badges.badge', verbose_name='Значок'),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Закреплён'),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='source',
            field=models.CharField(blank=True, max_length=64, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
