# Generated by Django 5.2.15 on 2026-06-16 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_squad_options_alter_track_options_and_more'),
        ('quests', '0004_selfreportproof'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quest',
            options={'verbose_name': 'Квест', 'verbose_name_plural': 'Квесты'},
        ),
        migrations.AlterModelOptions(
            name='questrewardtransaction',
            options={'verbose_name': 'Награда за квест', 'verbose_name_plural': 'Награды за квесты'},
        ),
        migrations.AlterModelOptions(
            name='seasonalevent',
            options={'verbose_name': 'Сезонная операция', 'verbose_name_plural': 'Сезонные операции'},
        ),
        migrations.AlterModelOptions(
            name='selfreportproof',
            options={'verbose_name': 'Самоотчёт', 'verbose_name_plural': 'Самоотчёты'},
        ),
        migrations.AlterModelOptions(
            name='squadleaderboardsnapshot',
            options={'verbose_name': 'Снимок рейтинга отряда', 'verbose_name_plural': 'Снимки рейтинга отрядов'},
        ),
        migrations.AlterModelOptions(
            name='userquestprogress',
            options={'verbose_name': 'Прогресс по квесту', 'verbose_name_plural': 'Прогресс по квестам'},
        ),
        migrations.RenameIndex(
            model_name='quest',
            new_name='quests_ques_is_acti_0b7c4f_idx',
            old_name='apps_quests_is_acti_3f1b8d_idx',
        ),
        migrations.RenameIndex(
            model_name='quest',
            new_name='quests_ques_start_a_1d3e61_idx',
            old_name='apps_quests_start_a_248911_idx',
        ),
        migrations.RenameIndex(
            model_name='questrewardtransaction',
            new_name='quests_ques_user_id_f78ad0_idx',
            old_name='apps_quests_user_id_06454f_idx',
        ),
        migrations.RenameIndex(
            model_name='seasonalevent',
            new_name='quests_seas_is_acti_0142df_idx',
            old_name='quests_seas_is_acti_425539_idx',
        ),
        migrations.RenameIndex(
            model_name='seasonalevent',
            new_name='quests_seas_started_14cdb1_idx',
            old_name='quests_seas_started_89f536_idx',
        ),
        migrations.RenameIndex(
            model_name='selfreportproof',
            new_name='quests_self_status_626392_idx',
            old_name='quests_self_status_9c1d3a_idx',
        ),
        migrations.RenameIndex(
            model_name='selfreportproof',
            new_name='quests_self_user_id_25a8af_idx',
            old_name='quests_self_user_id_41d4c3_idx',
        ),
        migrations.RenameIndex(
            model_name='squadleaderboardsnapshot',
            new_name='quests_squa_capture_e4ae0e_idx',
            old_name='quests_squa_captured_f5262e_idx',
        ),
        migrations.RenameIndex(
            model_name='squadleaderboardsnapshot',
            new_name='quests_squa_squad_i_b0061d_idx',
            old_name='quests_squa_squad_i_a33e78_idx',
        ),
        migrations.RenameIndex(
            model_name='userquestprogress',
            new_name='quests_user_user_id_71e146_idx',
            old_name='apps_quests_user_id_d7f95d_idx',
        ),
        migrations.RenameIndex(
            model_name='userquestprogress',
            new_name='quests_user_updated_b5c0e1_idx',
            old_name='apps_quests_updated_783116_idx',
        ),
        migrations.AlterField(
            model_name='quest',
            name='code',
            field=models.CharField(max_length=64, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='conditions',
            field=models.JSONField(blank=True, default=dict, verbose_name='Условия'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='quest_type',
            field=models.CharField(choices=[('daily', 'Ежедневный'), ('weekly', 'Еженедельный'), ('event', 'Событийный'), ('long', 'Долгий'), ('self_report', 'Самоотчёт'), ('mixed', 'Смешанный')], default='daily', max_length=16, verbose_name='Тип квеста'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='reward_coins',
            field=models.PositiveIntegerField(default=0, verbose_name='Награда (монеты)'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='reward_rating_delta',
            field=models.IntegerField(default=0, verbose_name='Награда (рейтинг)'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='questrewardtransaction',
            name='coins_delta',
            field=models.IntegerField(default=0, verbose_name='Монеты'),
        ),
        migrations.AlterField(
            model_name='questrewardtransaction',
            name='granted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Начислено'),
        ),
        migrations.AlterField(
            model_name='questrewardtransaction',
            name='progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_transactions', to='quests.userquestprogress', verbose_name='Прогресс'),
        ),
        migrations.AlterField(
            model_name='questrewardtransaction',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_transactions', to='quests.quest', verbose_name='Квест'),
        ),
        migrations.AlterField(
            model_name='questrewardtransaction',
            name='rating_delta',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='questrewardtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_rewards', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='seasonalevent',
            name='code',
            field=models.CharField(max_length=64, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='seasonalevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='seasonalevent',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='seasonalevent',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание'),
        ),
        migrations.AlterField(
            model_name='seasonalevent',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='seasonalevent',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Прогресс, %'),
        ),
        migrations.AlterField(
            model_name='seasonalevent',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='seasonalevent',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='selfreportproof',
            name='comment',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='selfreportproof',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='selfreportproof',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_report_proofs', to='quests.quest', verbose_name='Квест'),
        ),
        migrations.AlterField(
            model_name='selfreportproof',
            name='quest_progress',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='self_report_proof', to='quests.userquestprogress', verbose_name='Прогресс'),
        ),
        migrations.AlterField(
            model_name='selfreportproof',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки'),
        ),
        migrations.AlterField(
            model_name='selfreportproof',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='self_report_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Проверил'),
        ),
        migrations.AlterField(
            model_name='selfreportproof',
            name='status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], db_index=True, default='pending', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='selfreportproof',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_report_proofs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='squadleaderboardsnapshot',
            name='agents_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Число агентов'),
        ),
        migrations.AlterField(
            model_name='squadleaderboardsnapshot',
            name='avg_rating',
            field=models.FloatField(default=0, verbose_name='Средний рейтинг'),
        ),
        migrations.AlterField(
            model_name='squadleaderboardsnapshot',
            name='captured_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Снимок'),
        ),
        migrations.AlterField(
            model_name='squadleaderboardsnapshot',
            name='squad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_snapshots', to='accounts.squad', verbose_name='Отряд'),
        ),
        migrations.AlterField(
            model_name='userquestprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
        migrations.AlterField(
            model_name='userquestprogress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='userquestprogress',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Выполнен'),
        ),
        migrations.AlterField(
            model_name='userquestprogress',
            name='progress_value',
            field=models.FloatField(default=0, verbose_name='Прогресс'),
        ),
        migrations.AlterField(
            model_name='userquestprogress',
            name='proof_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные подтверждения'),
        ),
        migrations.AlterField(
            model_name='userquestprogress',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='quests.quest', verbose_name='Квест'),
        ),
        migrations.AlterField(
            model_name='userquestprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='userquestprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
