# Generated by Django 5.2.17 on 2026-08-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0006_questtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='period_key',
            field=models.CharField(blank=True, db_index=True, help_text='Дата для ежедневных квестов или неделя для еженедельных. Награда уникальна на пару «пользователь + квест», поэтому без отдельного экземпляра на период ежедневный квест оплачивался ровно один раз за всё время.', max_length=32, verbose_name='Период'),
        ),
        migrations.AddIndex(
            model_name='quest',
            index=models.Index(fields=['quest_type', 'period_key'], name='quests_ques_quest_t_30a767_idx'),
        ),
    ]
