# Generated by Django 5.2.17 on 2026-08-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0007_quest_period_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selfreportproof',
            options={'verbose_name': 'Подтверждение выполнения', 'verbose_name_plural': 'Подтверждения выполнения'},
        ),
        migrations.AddField(
            model_name='selfreportproof',
            name='attachment_link',
            field=models.URLField(blank=True, help_text='Ссылка на работу, репозиторий или фото — то, что проверяет куратор.', max_length=500, verbose_name='Ссылка на подтверждение'),
        ),
    ]
