# Generated by Django 5.2.17 on 2026-08-31 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0008_alter_selfreportproof_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_key', models.CharField(db_index=True, max_length=32, verbose_name='Неделя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Выбрана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменена')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focused_by', to='quests.quest', verbose_name='Квест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_focuses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Цель недели',
                'verbose_name_plural': 'Цели недели',
                'indexes': [models.Index(fields=['user', 'period_key'], name='quests_week_user_id_c58dbf_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'period_key'), name='uniq_weekly_focus_per_user')],
            },
        ),
    ]
