# Generated by Django 5.2.17 on 2026-09-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0009_weeklyfocus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questtemplate',
            name='verifier',
            field=models.CharField(choices=[('manual', 'Вручную'), ('hik_on_time', 'Hik: вовремя'), ('hik_no_late', 'Hik: без опозданий'), ('lxp_attendance', 'LXP: посещаемость'), ('lxp_ct_closed', 'LXP: закрытые КТ'), ('yougile_tasks', 'YouGile: задачи'), ('late_streak', 'Серия без опозданий'), ('lxp_no_misses', 'LXP: без пропусков занятий')], default='manual', max_length=32, verbose_name='Проверка'),
        ),
    ]
