# Generated by Django 5.2.15 on 2026-06-16 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Покупка', 'verbose_name_plural': 'Покупки'},
        ),
        migrations.AlterModelOptions(
            name='shopitem',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RenameIndex(
            model_name='purchase',
            new_name='shop_purcha_user_id_6d8e3b_idx',
            old_name='apps_shop_p_user_id_8da942_idx',
        ),
        migrations.RenameIndex(
            model_name='shopitem',
            new_name='shop_shopit_is_acti_f8919b_idx',
            old_name='apps_shop_s_is_acti_f843af_idx',
        ),
        migrations.RenameIndex(
            model_name='shopitem',
            new_name='shop_shopit_availab_f2fdcb_idx',
            old_name='apps_shop_s_availab_98fe84_idx',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='coins_spent',
            field=models.PositiveIntegerField(verbose_name='Потрачено монет'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='shop.shopitem', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='meta',
            field=models.JSONField(blank=True, default=dict, verbose_name='Метаданные'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='available_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Доступен с'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='available_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Доступен до'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='code',
            field=models.CharField(max_length=64, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='item_type',
            field=models.CharField(choices=[('cosmetic', 'Косметика'), ('boost', 'Усиление'), ('service', 'Услуга'), ('other', 'Прочее')], default='other', max_length=16, verbose_name='Тип товара'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='price_coins',
            field=models.PositiveIntegerField(verbose_name='Цена (монеты)'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
