# Generated by Django 5.2.17 on 2026-08-31 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_purchase_options_alter_shopitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='applied_at',
            field=models.DateTimeField(blank=True, help_text='Когда покупку сделали активной. Одновременно активна одна покупка на тип товара: рамка аватара, свечение значка и так далее.', null=True, verbose_name='Применена'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['user', 'applied_at'], name='shop_purcha_user_id_1252ae_idx'),
        ),
    ]
