# Generated by Django 5.2.15 on 2026-06-16 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duel',
            options={'verbose_name': 'Дуэль', 'verbose_name_plural': 'Дуэли'},
        ),
        migrations.AlterModelOptions(
            name='mentorship',
            options={'verbose_name': 'Наставничество', 'verbose_name_plural': 'Наставничества'},
        ),
        migrations.AlterModelOptions(
            name='respect',
            options={'verbose_name': 'Респект', 'verbose_name_plural': 'Респекты'},
        ),
        migrations.RenameIndex(
            model_name='duel',
            new_name='social_duel_status_4ee71d_idx',
            old_name='apps_social_status_1c254c_idx',
        ),
        migrations.RenameIndex(
            model_name='mentorship',
            new_name='social_ment_mentor__fa34e4_idx',
            old_name='apps_social_mentor__a54476_idx',
        ),
        migrations.RenameIndex(
            model_name='respect',
            new_name='social_resp_to_user_eb5003_idx',
            old_name='apps_social_to_user_a9d6e5_idx',
        ),
        migrations.AlterField(
            model_name='duel',
            name='challenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duels_started', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор'),
        ),
        migrations.AlterField(
            model_name='duel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='duel',
            name='opponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duels_received', to=settings.AUTH_USER_MODEL, verbose_name='Соперник'),
        ),
        migrations.AlterField(
            model_name='duel',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершён'),
        ),
        migrations.AlterField(
            model_name='duel',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принят'), ('rejected', 'Отклонён')], default='pending', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='mentorship',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание'),
        ),
        migrations.AlterField(
            model_name='mentorship',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to=settings.AUTH_USER_MODEL, verbose_name='Подопечный'),
        ),
        migrations.AlterField(
            model_name='mentorship',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentees', to=settings.AUTH_USER_MODEL, verbose_name='Наставник'),
        ),
        migrations.AlterField(
            model_name='mentorship',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='respect',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='respect',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respects_given', to=settings.AUTH_USER_MODEL, verbose_name='От кого'),
        ),
        migrations.AlterField(
            model_name='respect',
            name='message',
            field=models.CharField(blank=True, max_length=255, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='respect',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respects_received', to=settings.AUTH_USER_MODEL, verbose_name='Кому'),
        ),
    ]
