# Generated by Django 5.2.13 on 2026-08-15 21:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_duel_options_alter_mentorship_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mentorship',
            constraint=models.CheckConstraint(condition=models.Q(('mentor', models.F('mentee')), _negated=True), name='social_mentorship_mentor_ne_mentee'),
        ),
    ]
