# Generated by Django 5.2.17 on 2026-08-31 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_mentorship_social_mentorship_mentor_ne_mentee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='duel',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Принят'),
        ),
        migrations.AddField(
            model_name='duel',
            name='bet_coins',
            field=models.PositiveIntegerField(default=0, verbose_name='Ставка (монеты)'),
        ),
        migrations.AddField(
            model_name='duel',
            name='challenger_rating_start',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рейтинг инициатора на старте'),
        ),
        migrations.AddField(
            model_name='duel',
            name='opponent_rating_start',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рейтинг соперника на старте'),
        ),
        migrations.AddField(
            model_name='duel',
            name='resolve_after',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Подводить итог после'),
        ),
        migrations.AddField(
            model_name='duel',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duels_won', to=settings.AUTH_USER_MODEL, verbose_name='Победитель'),
        ),
        migrations.AlterField(
            model_name='duel',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принят'), ('rejected', 'Отклонён'), ('finished', 'Завершён')], default='pending', max_length=16, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='duel',
            index=models.Index(fields=['status', 'resolve_after'], name='social_duel_status_52e7a1_idx'),
        ),
    ]
